version: '2'

services:
  xld-service:
    image: xldeploy:6.0.0
    ports:
       - "4516:4516"
    labels:
      io.rancher.container.pull_image: always
    environment:
      - PLUGINS_FILE_URL=${XLD_PLUGINS_FILE_URL}
  xlr-service:
    image: xlrelease:6.0.0
    ports:
       - "5516:5516"
    labels:
      io.rancher.container.pull_image: always
    environment:
      - PLUGINS_FILE_URL=${XLR_PLUGINS_FILE_URL}
  jenkins-service:
    image: rbcdjenkins:1.0
    ports:
       - "8080:8080"
    labels:
      io.rancher.container.pull_image: always
    environment:
      - JENKINS_UC_DOWNLOAD=${JENKINS_UC_DOWNLOAD}
      - PLUGINS_FILE_URL=${JENKINS_PLUGINS_FILE_URL}
